[REFACTOR]: Refactor components and useFetchNotifications
JWAT-CTRL-C/client pull request #74
Opened 2024-06-30 17:00 UTC by ZLoganZ

This pull request includes refactoring of components and the useFetchNotifications hook. The refactoring removes unused code and updates the useFetchNotifications hook to directly return notifications.

2024-06-30 17:16 UTC, quangvinht approved these changes

2024-06-30 17:35 UTC, Kreal244 requested changes

2024-06-30 17:35 UTC, Kreal244 commented on components/workspaces/WpsMemberTable.tsx
ủa gì đây

2024-06-30 17:35 UTC, Kreal244 commented on components/workspaces/WpsMemberTable.tsx
> +    if (member.owner.user_id !== currentUser.user_id && !['MA', 'HM'].includes(currentUser.role))
xoá cái này => if (member.owner.user_id !== currentUser.user_id && !['MA', 'HM'].includes(currentUser.role))
      router.replace(`/workspaces/${wksp_id}`);

2024-06-30 17:35 UTC, Kreal244 commented on components/workspaces/editMemberForm.tsx
>    useEffect(() => {
thay   useEffect(() => {
  thành   useEffect(() => {
    if (
      !_.isNil(members) &&
      members.owner.user_id !== currentUser.user_id &&
      !['MA', 'HM'].includes(currentUser.role)
    ) {
      router.replace(`/workspaces/${router.query.id}`);
    }

2024-07-01 01:42 UTC, ZLoganZ commented on components/workspaces/WpsMemberTable.tsx
> +    if (member.owner.user_id !== currentUser.user_id && !['MA', 'HM'].includes(currentUser.role))
sao xoa vay

2024-07-01 02:09 UTC, Kreal244 approved these changes

2024-07-01 02:09 UTC, merged